#!/usr/bin/env python3.10
from keboola.component.dao import BaseType, ColumnDefinition, SupportedDataTypes, logging
import tempo
from typing import Any


_TABLE_WL_ATTR = "worklog_attributes"
_TABLE_WL_ATTR_CONFIG = "worklog_attributes_config"

FILENAME_WL_ATTR = "worklog_attributes.csv"
FILENAME_WL_ATTR_CONFIG = "worklog_attributes_config.csv"

_ATTR_COL_WORKLOG_ID = "tempo_worklog_id"
_ATTR_COL_ATTRIBUTE_KEY = "attribute_key"
_ATTR_COL_ATTRIBUTE_VALUE = "attribute_value"

_CONF_COL_ATTRIBUTE_KEY = "attribute_key"
_CONF_COL_ATTRIBUTE_NAME = "attribute_name"
_CONF_COL_ATTRIBUTE_TYPE = "attribute_type"
_CONF_COL_ATTRIBUTE_VALUES = "attribute_values"


def column_definitions() -> dict[str, Any]:
    return {
        _TABLE_WL_ATTR: {
            _ATTR_COL_WORKLOG_ID: ColumnDefinition(
                data_types=BaseType(dtype=SupportedDataTypes.INTEGER),
                nullable=False,
                primary_key=True,
                description="ID of associated worklog in Tempo system"
            ),
            _ATTR_COL_ATTRIBUTE_KEY: ColumnDefinition(
                data_types=BaseType(dtype=SupportedDataTypes.STRING, length=300),
                nullable=False,
                primary_key=True,
                description="Attribute key"
            ),
            _ATTR_COL_ATTRIBUTE_VALUE: ColumnDefinition(
                data_types=BaseType(dtype=SupportedDataTypes.STRING, length=300),
                nullable=False,
                primary_key=False,
                description="Attribute value"
            )
        },
        _TABLE_WL_ATTR_CONFIG: {
            _CONF_COL_ATTRIBUTE_KEY: ColumnDefinition(
                data_types=BaseType(dtype=SupportedDataTypes.STRING, length=300),
                nullable=False,
                primary_key=True,
                description="Attribute key that is generated by Tempo system"
            ),
            _CONF_COL_ATTRIBUTE_NAME: ColumnDefinition(
                data_types=BaseType(dtype=SupportedDataTypes.STRING, length=400),
                nullable=False,
                primary_key=False,
                description="Human readable name that is shown in UI"
            ),
            _CONF_COL_ATTRIBUTE_TYPE: ColumnDefinition(
                data_types=BaseType(dtype=SupportedDataTypes.STRING, length=300),
                nullable=False,
                primary_key=False,
                description="Attribute value type"
            ),
            _CONF_COL_ATTRIBUTE_VALUES: ColumnDefinition(
                data_types=BaseType(dtype=SupportedDataTypes.STRING, length=8000),
                nullable=False,
                primary_key=False,
                description="Attribute value id to value mapping table"
            )
        }
    }


def run(worklogs: list) -> list[dict[str, Any]]:
    """
    worklogs: list - previously loaded worklogs so we don't double load
    """
    if worklogs is None or len(worklogs) == 0:
        logging.error("no worklogs provided")
        return {
            _TABLE_WL_ATTR: [],
            _TABLE_WL_ATTR_CONFIG: []
        }
    logging.info(f"Started loading worklog attributes for {len(worklogs)} number of worklogs")
    buffer_size = 400
    buffer_start = 0
    attribute_data = []
    while False:
        buffered_worklogs = worklogs[buffer_start:buffer_start+buffer_size]
        buffer_start += buffer_size
        attributes = tempo.worklog_attributes(buffered_worklogs)
        if attributes is not None:
            attribute_data.append(attributes)
    logging.info("Finished loading worklog attributes")
    return {
        _TABLE_WL_ATTR: attribute_data
    }
